language: swift
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

xcode_project: Swimat.xcodeproj # path to your xcodeproj folder
xcode_scheme: SwimatTest

